# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pre-Release

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]

permissions:
  contents: write

jobs:
  semver:
    runs-on: ubuntu-latest
    name: Update Version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run TinySemVer
        uses: ./ # This uses the action defined in the current repository
        with:
          verbose: "true"
          changelog-file: "CHANGELOG.md"
          version-file: "VERSION"
          update-version-in: 'pyproject.toml:version = "(.*)"'
          dry-run: "true"
