# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  semver:
    runs-on: ubuntu-latest
    name: Update Version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run TinySemVer
        uses: ./ # This uses the action defined in the current repository
        with:
          verbose: "true"
          push: "true"
          changelog-file: "CHANGELOG.md"
          version-file: "VERSION"
          update-version-in: 'pyproject.toml:version = "(.*)"'
          github-token: ${{ secrets.TINYSEMVER_TOKEN }}
          create-release: "true"

  publish_python:
    name: Publish Python
    runs-on: ubuntu-latest
    needs: semver
    environment:
      name: pypi
      url: https://pypi.org/p/tinysemver
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
